### ISSUE TITLE
Ошибки автоперевода в статье

### ISSUE THREAD

**Issue by laticq** [MicrosoftDocs/windowsserverdocs.ru-ru#1]
Примеры ошибок надмозга:
- используйте 1 МБ **`Блокксизебитес`**
- отсутствует таймер «**`СМОЛой`**»
- В файле **`ефидефаулт`** на PxE-сервере
- измените **`/Бут/груб/груб.конф,/т.п./`**`default/grub`
- в конфигураци**и** загрузчика (например,`/ЕТК/`**`груб.конф`**) добавьте **`Лифт`** = NOOP
- больше памяти для **`кдумп`**
и тд. 

Это забавно)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 17bc364f-8fd0-b273-50bc-63a0d240f8d0
* Version Independent ID: dd4c402b-1f9f-f3d9-bb98-4b9c2c20f04a
* Content: [Рекомендации по запуску Linux в Hyper-V](https://docs.microsoft.com/ru-ru/windows-server/virtualization/hyper-v/best-practices-for-running-linux-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs.ru-ru/blob/live/WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by srvbpigh** [comment]
Hello, @laticq
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @laticq 
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
