### ISSUE TITLE
Проблема 

### ISSUE THREAD

**Issue by Antoxa106** [MicrosoftDocs/windowsserverdocs.ru-ru#10]
Не отображаеться Рис.1 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2aa81041-3a2a-961a-05d5-4a845cc74ae2
* Version Independent ID: fadf165a-5c81-0102-e096-7f527483313b
* Content: [Перенос файлового сервера с помощью службы миграции хранилища](https://docs.microsoft.com/ru-ru/windows-server/storage/storage-migration-service/migrate-data#feedback)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs.ru-ru/blob/live/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @Antoxa106
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Antoxa106 

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
