### ISSUE TITLE
Вообще не помогла статья - только завела в тупик

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [MicrosoftDocs/windowsserverdocs.ru-ru#11]
Потеряв в итоге целый день - выяснил, что если диск С и загрузочный раздел установлены на диске, то их нельзя удалить, а потому и преобразовать в базовый... Мне нужно было решить этот вопрос для паралелльной установки Linux В итого пришлось вообще снести Windows к черту

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 722fedef-d6a4-5ed6-526b-d6dd1a4d0642
* Version Independent ID: 10f9b44a-5a88-cb84-293f-1baf62359299
* Content: [Преобразование динамического диска в базовый](https://docs.microsoft.com/ru-ru/windows-server/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs.ru-ru/blob/live/WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by srvbpigh** [comment]
Hello, @Morgunov-Vitaly
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Morgunov-Vitaly 

Благодарим Вас за вклад. Да, этот отзыв связан с продуктом. Отправьте свое предложение, нажав кнопку "Отправить отзыв по продукту" в нижней части страницы документации. 

Если вы хотите поделиться своим мнением о документации, отправьте его по этому каналу. 

Благодарим за Ваш вклад в улучшение наших статей. 

Международная команда поддержки документации Microsoft
