### ISSUE TITLE
Прекрасно поданный материал. 

### ISSUE THREAD

**Issue by GarricRus** [MicrosoftDocs/windowsserverdocs.ru-ru#14]
Прекрасно поданный материал. 
Особенно понравился пинг порта: psping -accepteula &lt;computer IP&gt;:3389
, о чём никогда не упоминается в статьях про блокирование доступа .фаерволом.
Написано настолько хорошо и понятно, что материал легко может переносится и на другие проблемы с доступом, будь то WMI или что то другое.
Спасибо автору.
Материал, вне всяких сомнений, скопирую себе в качестве наставления.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 420f2431-a31d-c952-eec9-47399399e151
* Version Independent ID: c00b4f63-1ddf-27b5-835b-35f7d6d80484
* Content: [Устранение неполадок с подключениями к Удаленному рабочему столу](https://docs.microsoft.com/ru-ru/windows-server/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs.ru-ru/blob/live/WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md)
* GitHub Login: @kaushika-msft
* Microsoft Alias: **delhan**

**Comment by srvbpigh** [comment]
Hello, @GarricRus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @GarricRus  

Благодарим Вас за отзыв. Мы рады, что работа с нашей документацией соответствует Вашим ожиданиям.  

Надеемся получить от Вас и другие полезные отзывы, которые помогут нам улучшать работу и дальше.  

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
