### ISSUE TITLE
translate error

### ISSUE THREAD

**Issue by iv777** [MicrosoftDocs/windowsserverdocs.ru-ru#2]
In russian version
https://docs.microsoft.com/ru-ru/windows-server/manage/windows-admin-center/support/troubleshooting
I see:
For an easy way to set all TrustedHosts at once, you can use a wildcard.
&lt;span data-ttu-id="ff664-179"&gt;Set-Item WSMan:\localhost\Client\TrustedHosts -Value '\*'&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="ff664-179"&gt;Set-Item WSMan:\localhost\Client\TrustedHosts -Value '\*'&lt;/span&gt;&lt;/span&gt;

In english 
https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting
It is look ok:
For an easy way to set all TrustedHosts at once, you can use a wildcard.
Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*'

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1e5fc70f-7d73-a27a-dd16-caf965c849d0
* Version Independent ID: c0c463f4-52f4-3582-87fd-edd2c5263871
* Content: [Windows Admin Center: общие действия по устранению неполадок](https://docs.microsoft.com/ru-ru/windows-server/manage/windows-admin-center/support/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs.ru-ru/blob/live/WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by srvbpigh** [comment]
Hello, @iv777
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @iv777, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3716. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
